/* eslint-disable react/no-unknown-property */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh009: THREE.Mesh
    mesh009_1: THREE.Mesh
    mesh_1147796766: THREE.Mesh
    mesh072: THREE.Mesh
    mesh072_1: THREE.Mesh
    mesh072_2: THREE.Mesh
    mesh072_3: THREE.Mesh
    mesh072_4: THREE.Mesh
    mesh074: THREE.Mesh
    mesh074_1: THREE.Mesh
    mesh074_2: THREE.Mesh
    mesh074_3: THREE.Mesh
    mesh074_4: THREE.Mesh
    mesh012: THREE.Mesh
    mesh012_1: THREE.Mesh
    mesh012_2: THREE.Mesh
    mesh012_3: THREE.Mesh
    mesh012_4: THREE.Mesh
    mesh012_5: THREE.Mesh
    mesh012_6: THREE.Mesh
    mesh012_7: THREE.Mesh
    mesh012_8: THREE.Mesh
    mesh012_9: THREE.Mesh
    mesh012_10: THREE.Mesh
    mesh012_11: THREE.Mesh
    mesh012_12: THREE.Mesh
    mesh012_13: THREE.Mesh
    mesh012_14: THREE.Mesh
    mesh012_15: THREE.Mesh
    mesh012_16: THREE.Mesh
    mesh012_17: THREE.Mesh
    mesh012_18: THREE.Mesh
    mesh012_19: THREE.Mesh
    mesh012_20: THREE.Mesh
    mesh012_21: THREE.Mesh
    mesh012_22: THREE.Mesh
    mesh012_23: THREE.Mesh
    mesh012_24: THREE.Mesh
    mesh012_25: THREE.Mesh
    mesh012_26: THREE.Mesh
    mesh012_27: THREE.Mesh
    mesh012_28: THREE.Mesh
    mesh012_29: THREE.Mesh
    mesh012_30: THREE.Mesh
    mesh012_31: THREE.Mesh
    mesh012_32: THREE.Mesh
    mesh012_33: THREE.Mesh
    mesh012_34: THREE.Mesh
    mesh012_35: THREE.Mesh
    mesh012_36: THREE.Mesh
    mesh012_37: THREE.Mesh
    mesh012_38: THREE.Mesh
    mesh012_39: THREE.Mesh
    mesh012_40: THREE.Mesh
    mesh012_41: THREE.Mesh
    mesh012_42: THREE.Mesh
    mesh012_43: THREE.Mesh
    mesh012_44: THREE.Mesh
    mesh_1520030306: THREE.Mesh
    mesh_1661526548: THREE.Mesh
    mesh_2044287231: THREE.Mesh
    mesh_226909013: THREE.Mesh
    mesh069: THREE.Mesh
    mesh069_1: THREE.Mesh
    mesh069_2: THREE.Mesh
    mesh069_3: THREE.Mesh
    mesh069_4: THREE.Mesh
    mesh069_5: THREE.Mesh
    mesh069_6: THREE.Mesh
    mesh069_7: THREE.Mesh
    mesh069_8: THREE.Mesh
    mesh069_9: THREE.Mesh
    mesh069_10: THREE.Mesh
    mesh069_11: THREE.Mesh
    mesh069_12: THREE.Mesh
    mesh069_13: THREE.Mesh
    mesh069_14: THREE.Mesh
    mesh069_15: THREE.Mesh
    mesh069_16: THREE.Mesh
    mesh069_17: THREE.Mesh
    mesh069_18: THREE.Mesh
    mesh069_19: THREE.Mesh
    mesh069_20: THREE.Mesh
    mesh069_21: THREE.Mesh
    mesh069_22: THREE.Mesh
    mesh069_23: THREE.Mesh
    mesh069_24: THREE.Mesh
    mesh069_25: THREE.Mesh
    mesh069_26: THREE.Mesh
    mesh069_27: THREE.Mesh
    mesh085: THREE.Mesh
    mesh085_1: THREE.Mesh
    mesh085_2: THREE.Mesh
    mesh085_3: THREE.Mesh
    mesh085_4: THREE.Mesh
    mesh085_5: THREE.Mesh
    mesh085_6: THREE.Mesh
    mesh085_7: THREE.Mesh
    mesh085_8: THREE.Mesh
    mesh085_9: THREE.Mesh
    mesh_402308287: THREE.Mesh
    mesh086: THREE.Mesh
    mesh086_1: THREE.Mesh
    mesh086_2: THREE.Mesh
    mesh093: THREE.Mesh
    mesh093_1: THREE.Mesh
    mesh_630431113: THREE.Mesh
    mesh091: THREE.Mesh
    mesh091_1: THREE.Mesh
    mesh091_2: THREE.Mesh
    mesh091_3: THREE.Mesh
    mesh091_4: THREE.Mesh
    mesh091_5: THREE.Mesh
    mesh007: THREE.Mesh
    mesh007_1: THREE.Mesh
    mesh007_2: THREE.Mesh
    mesh_966850892: THREE.Mesh
  }
  materials: {
    material_17___13053: THREE.MeshStandardMaterial
    material_20___13053: THREE.MeshStandardMaterial
    ['material_18___13053.009']: THREE.MeshStandardMaterial
    ['material_19___13053.009']: THREE.MeshStandardMaterial
    ['material_20___13053.003']: THREE.MeshStandardMaterial
    ['material_15___13053.072']: THREE.MeshStandardMaterial
    ['material_16___13053.072']: THREE.MeshStandardMaterial
    ['material_15___13053.071']: THREE.MeshStandardMaterial
    ['material_17___13053.071']: THREE.MeshStandardMaterial
    ['material_23___13053.071']: THREE.MeshStandardMaterial
    ['material_15___13053.074']: THREE.MeshStandardMaterial
    ['material_17___13053.011']: THREE.MeshStandardMaterial
    ['material_22___13053.011']: THREE.MeshStandardMaterial
    ['material_23___13053.047']: THREE.MeshStandardMaterial
    ['material_15___13053.073']: THREE.MeshStandardMaterial
    ['material_16___13053.012']: THREE.MeshStandardMaterial
    ['material_16___13053.010']: THREE.MeshStandardMaterial
    ['material_22___13053.010']: THREE.MeshStandardMaterial
    ['material_15___13053.013']: THREE.MeshStandardMaterial
    ['material_15___13053.014']: THREE.MeshStandardMaterial
    ['material_15___13053.015']: THREE.MeshStandardMaterial
    ['material_15___13053.016']: THREE.MeshStandardMaterial
    ['material_15___13053.017']: THREE.MeshStandardMaterial
    ['material_15___13053.018']: THREE.MeshStandardMaterial
    ['material_15___13053.019']: THREE.MeshStandardMaterial
    ['material_15___13053.020']: THREE.MeshStandardMaterial
    ['material_15___13053.021']: THREE.MeshStandardMaterial
    ['material_15___13053.022']: THREE.MeshStandardMaterial
    ['material_15___13053.023']: THREE.MeshStandardMaterial
    ['material_15___13053.024']: THREE.MeshStandardMaterial
    ['material_15___13053.025']: THREE.MeshStandardMaterial
    ['material_15___13053.026']: THREE.MeshStandardMaterial
    ['material_15___13053.027']: THREE.MeshStandardMaterial
    ['material_15___13053.028']: THREE.MeshStandardMaterial
    ['material_15___13053.029']: THREE.MeshStandardMaterial
    ['material_15___13053.030']: THREE.MeshStandardMaterial
    ['material_15___13053.031']: THREE.MeshStandardMaterial
    ['material_15___13053.032']: THREE.MeshStandardMaterial
    ['material_15___13053.033']: THREE.MeshStandardMaterial
    ['material_15___13053.034']: THREE.MeshStandardMaterial
    ['material_15___13053.035']: THREE.MeshStandardMaterial
    ['material_15___13053.036']: THREE.MeshStandardMaterial
    ['material_15___13053.037']: THREE.MeshStandardMaterial
    ['material_15___13053.038']: THREE.MeshStandardMaterial
    ['material_15___13053.039']: THREE.MeshStandardMaterial
    ['material_15___13053.040']: THREE.MeshStandardMaterial
    ['material_15___13053.041']: THREE.MeshStandardMaterial
    ['material_15___13053.042']: THREE.MeshStandardMaterial
    ['material_15___13053.043']: THREE.MeshStandardMaterial
    ['material_15___13053.044']: THREE.MeshStandardMaterial
    ['material_15___13053.049']: THREE.MeshStandardMaterial
    ['material_15___13053.050']: THREE.MeshStandardMaterial
    ['material_15___13053.051']: THREE.MeshStandardMaterial
    ['material_15___13053.055']: THREE.MeshStandardMaterial
    ['material_15___13053.057']: THREE.MeshStandardMaterial
    ['material_15___13053.058']: THREE.MeshStandardMaterial
    ['material_15___13053.059']: THREE.MeshStandardMaterial
    ['material_15___13053.065']: THREE.MeshStandardMaterial
    ['material_15___13053.066']: THREE.MeshStandardMaterial
    ['material_15___13053.067']: THREE.MeshStandardMaterial
    ['material_20___13053.004']: THREE.MeshStandardMaterial
    ['material_21___13053.008']: THREE.MeshStandardMaterial
    ['material_20___13053.001']: THREE.MeshStandardMaterial
    ['material_20___13053.002']: THREE.MeshStandardMaterial
    ['material_15___13053.069']: THREE.MeshStandardMaterial
    ['material_16___13053.069']: THREE.MeshStandardMaterial
    ['material_15___13053.045']: THREE.MeshStandardMaterial
    ['material_16___13053.045']: THREE.MeshStandardMaterial
    ['material_15___13053.046']: THREE.MeshStandardMaterial
    ['material_16___13053.046']: THREE.MeshStandardMaterial
    ['material_15___13053.048']: THREE.MeshStandardMaterial
    ['material_16___13053.048']: THREE.MeshStandardMaterial
    ['material_8___13053.052']: THREE.MeshStandardMaterial
    ['material_21___13053.052']: THREE.MeshStandardMaterial
    ['material_15___13053.053']: THREE.MeshStandardMaterial
    ['material_16___13053.053']: THREE.MeshStandardMaterial
    ['material_15___13053.054']: THREE.MeshStandardMaterial
    ['material_16___13053.054']: THREE.MeshStandardMaterial
    ['material_15___13053.056']: THREE.MeshStandardMaterial
    ['material_16___13053.056']: THREE.MeshStandardMaterial
    ['material_15___13053.060']: THREE.MeshStandardMaterial
    ['material_16___13053.060']: THREE.MeshStandardMaterial
    ['material_15___13053.061']: THREE.MeshStandardMaterial
    ['material_16___13053.061']: THREE.MeshStandardMaterial
    ['material_15___13053.062']: THREE.MeshStandardMaterial
    ['material_16___13053.062']: THREE.MeshStandardMaterial
    ['material_15___13053.063']: THREE.MeshStandardMaterial
    ['material_16___13053.063']: THREE.MeshStandardMaterial
    ['material_15___13053.064']: THREE.MeshStandardMaterial
    ['material_16___13053.064']: THREE.MeshStandardMaterial
    ['material_15___13053.068']: THREE.MeshStandardMaterial
    ['material_16___13053.068']: THREE.MeshStandardMaterial
    ['material_20___13053.085']: THREE.MeshStandardMaterial
    ['material_17___13053.075']: THREE.MeshStandardMaterial
    ['material_20___13053.076']: THREE.MeshStandardMaterial
    ['material_20___13053.077']: THREE.MeshStandardMaterial
    ['material_20___13053.078']: THREE.MeshStandardMaterial
    ['material_20___13053.079']: THREE.MeshStandardMaterial
    ['material_20___13053.080']: THREE.MeshStandardMaterial
    ['material_20___13053.082']: THREE.MeshStandardMaterial
    ['material_20___13053.083']: THREE.MeshStandardMaterial
    ['material_20___13053.084']: THREE.MeshStandardMaterial
    ['material_15___13053.092']: THREE.MeshStandardMaterial
    ['material_16___13053.086']: THREE.MeshStandardMaterial
    ['material_17___13053.086']: THREE.MeshStandardMaterial
    ['material_23___13053.086']: THREE.MeshStandardMaterial
    ['material_16___13053.093']: THREE.MeshStandardMaterial
    ['material_22___13053.093']: THREE.MeshStandardMaterial
    ['material_20___13053.081']: THREE.MeshStandardMaterial
    ['material_16___13053.091']: THREE.MeshStandardMaterial
    ['material_18___13053.087']: THREE.MeshStandardMaterial
    ['material_19___13053.087']: THREE.MeshStandardMaterial
    ['material_20___13053.088']: THREE.MeshStandardMaterial
    ['material_20___13053.089']: THREE.MeshStandardMaterial
    ['material_16___13053.090']: THREE.MeshStandardMaterial
    ['material_21___13053.007']: THREE.MeshStandardMaterial
    ['material_20___13053.006']: THREE.MeshStandardMaterial
    ['material_21___13053.006']: THREE.MeshStandardMaterial
    ['material_21___13053.005']: THREE.MeshStandardMaterial
  }
}

export function StudyDesk(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    'models/studyDesk.glb',
  ) as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.0098}>
          {/* 椅子 */}
          <group
            rotation-z={-Math.PI * 0.25}
            position={[35, 30, 0]}
            scale={1.05}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh_630431113.geometry}
              material={materials['material_20___13053.081']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085.geometry}
              material={materials['material_20___13053.085']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085_1.geometry}
              material={materials['material_17___13053.075']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085_2.geometry}
              material={materials['material_20___13053.076']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085_3.geometry}
              material={materials['material_20___13053.077']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085_4.geometry}
              material={materials['material_20___13053.078']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085_5.geometry}
              material={materials['material_20___13053.079']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085_6.geometry}
              material={materials['material_20___13053.080']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085_7.geometry}
              material={materials['material_20___13053.082']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085_8.geometry}
              material={materials['material_20___13053.083']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh085_9.geometry}
              material={materials['material_20___13053.084']}
            />
          </group>

          <group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh.geometry}
              material={materials.material_17___13053}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh_1.geometry}
              material={materials.material_20___13053}
            />
          </group>
          <group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh009.geometry}
              material={materials['material_18___13053.009']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh009_1.geometry}
              material={materials['material_19___13053.009']}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_1147796766.geometry}
            material={materials['material_20___13053.003']}
          />
          <group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh072.geometry}
              material={materials['material_15___13053.072']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh072_1.geometry}
              material={materials['material_16___13053.072']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh072_2.geometry}
              material={materials['material_15___13053.071']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh072_3.geometry}
              material={materials['material_17___13053.071']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh072_4.geometry}
              material={materials['material_23___13053.071']}
            />
          </group>
          <group position={[87.17, 23.91, -145.28]} rotation={[0, 0, 0.07]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh074.geometry}
              material={materials['material_15___13053.074']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh074_1.geometry}
              material={materials['material_17___13053.011']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh074_2.geometry}
              material={materials['material_22___13053.011']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh074_3.geometry}
              material={materials['material_23___13053.047']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh074_4.geometry}
              material={materials['material_15___13053.073']}
            />
          </group>
          <group position={[86.69, 24.41, -145.49]} rotation={[0, 0, 0.07]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012.geometry}
              material={materials['material_16___13053.012']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_1.geometry}
              material={materials['material_16___13053.010']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_2.geometry}
              material={materials['material_22___13053.010']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_3.geometry}
              material={materials['material_15___13053.013']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_4.geometry}
              material={materials['material_15___13053.014']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_5.geometry}
              material={materials['material_15___13053.015']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_6.geometry}
              material={materials['material_15___13053.016']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_7.geometry}
              material={materials['material_15___13053.017']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_8.geometry}
              material={materials['material_15___13053.018']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_9.geometry}
              material={materials['material_15___13053.019']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_10.geometry}
              material={materials['material_15___13053.020']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_11.geometry}
              material={materials['material_15___13053.021']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_12.geometry}
              material={materials['material_15___13053.022']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_13.geometry}
              material={materials['material_15___13053.023']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_14.geometry}
              material={materials['material_15___13053.024']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_15.geometry}
              material={materials['material_15___13053.025']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_16.geometry}
              material={materials['material_15___13053.026']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_17.geometry}
              material={materials['material_15___13053.027']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_18.geometry}
              material={materials['material_15___13053.028']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_19.geometry}
              material={materials['material_15___13053.029']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_20.geometry}
              material={materials['material_15___13053.030']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_21.geometry}
              material={materials['material_15___13053.031']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_22.geometry}
              material={materials['material_15___13053.032']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_23.geometry}
              material={materials['material_15___13053.033']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_24.geometry}
              material={materials['material_15___13053.034']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_25.geometry}
              material={materials['material_15___13053.035']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_26.geometry}
              material={materials['material_15___13053.036']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_27.geometry}
              material={materials['material_15___13053.037']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_28.geometry}
              material={materials['material_15___13053.038']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_29.geometry}
              material={materials['material_15___13053.039']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_30.geometry}
              material={materials['material_15___13053.040']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_31.geometry}
              material={materials['material_15___13053.041']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_32.geometry}
              material={materials['material_15___13053.042']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_33.geometry}
              material={materials['material_15___13053.043']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_34.geometry}
              material={materials['material_15___13053.044']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_35.geometry}
              material={materials['material_15___13053.049']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_36.geometry}
              material={materials['material_15___13053.050']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_37.geometry}
              material={materials['material_15___13053.051']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_38.geometry}
              material={materials['material_15___13053.055']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_39.geometry}
              material={materials['material_15___13053.057']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_40.geometry}
              material={materials['material_15___13053.058']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_41.geometry}
              material={materials['material_15___13053.059']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_42.geometry}
              material={materials['material_15___13053.065']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_43.geometry}
              material={materials['material_15___13053.066']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh012_44.geometry}
              material={materials['material_15___13053.067']}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_1520030306.geometry}
            material={materials['material_20___13053.004']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_1661526548.geometry}
            material={materials['material_21___13053.008']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_2044287231.geometry}
            material={materials['material_20___13053.001']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_226909013.geometry}
            material={materials['material_20___13053.002']}
          />
          <group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069.geometry}
              material={materials['material_15___13053.069']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_1.geometry}
              material={materials['material_16___13053.069']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_2.geometry}
              material={materials['material_15___13053.045']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_3.geometry}
              material={materials['material_16___13053.045']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_4.geometry}
              material={materials['material_15___13053.046']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_5.geometry}
              material={materials['material_16___13053.046']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_6.geometry}
              material={materials['material_15___13053.048']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_7.geometry}
              material={materials['material_16___13053.048']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_8.geometry}
              material={materials['material_8___13053.052']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_9.geometry}
              material={materials['material_21___13053.052']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_10.geometry}
              material={materials['material_15___13053.053']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_11.geometry}
              material={materials['material_16___13053.053']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_12.geometry}
              material={materials['material_15___13053.054']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_13.geometry}
              material={materials['material_16___13053.054']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_14.geometry}
              material={materials['material_15___13053.056']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_15.geometry}
              material={materials['material_16___13053.056']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_16.geometry}
              material={materials['material_15___13053.060']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_17.geometry}
              material={materials['material_16___13053.060']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_18.geometry}
              material={materials['material_15___13053.061']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_19.geometry}
              material={materials['material_16___13053.061']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_20.geometry}
              material={materials['material_15___13053.062']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_21.geometry}
              material={materials['material_16___13053.062']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_22.geometry}
              material={materials['material_15___13053.063']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_23.geometry}
              material={materials['material_16___13053.063']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_24.geometry}
              material={materials['material_15___13053.064']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_25.geometry}
              material={materials['material_16___13053.064']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_26.geometry}
              material={materials['material_15___13053.068']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh069_27.geometry}
              material={materials['material_16___13053.068']}
            />
          </group>

          <mesh
            castShadow
            receiveShadow
            geometry={nodes.mesh_402308287.geometry}
            material={materials['material_15___13053.092']}
          />
          <group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh093.geometry}
              material={materials['material_16___13053.093']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh093_1.geometry}
              material={materials['material_22___13053.093']}
            />
          </group>

          <group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh091.geometry}
              material={materials['material_16___13053.091']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh091_1.geometry}
              material={materials['material_18___13053.087']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh091_2.geometry}
              material={materials['material_19___13053.087']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh091_3.geometry}
              material={materials['material_20___13053.088']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh091_4.geometry}
              material={materials['material_20___13053.089']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh091_5.geometry}
              material={materials['material_16___13053.090']}
            />
          </group>
          <group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh007.geometry}
              material={materials['material_21___13053.007']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh007_1.geometry}
              material={materials['material_20___13053.006']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.mesh007_2.geometry}
              material={materials['material_21___13053.006']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/studyDesk.glb')
