version: '3'
services:
  app:
    build:
     context: .
     dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      # node_modulesがホストのカレントディレクトリに共有されないようボリュームに切り出し
      - node_modules:/app/node_modules
      # ホストのカレントディレクトリをコンテナの/appにバインドマウントして共有
      - ./:/app:cached
volumes:
  node_modules: {}